import { hType } from '../../defs/def-events';
import type { FishCatalogEntry } from '../../defs/def-record';

export const defaultFishCatalog: FishCatalogEntry[] = [
	{fishName: 'Anchovy', baseline: 2.5, fishFlavor: 'i like them on pizza!', fishColor: hType.navy},
	{fishName: 'Angelfish', baseline: 6, fishFlavor: 'i bet it tastes heavenly!', fishColor: hType.yellow},
	{fishName: 'Barracuda', baseline: 200, fishFlavor: 'how much barra cuda barracuda barra if a barracuda cuda barra?', fishColor: hType.navy},
	{fishName: 'Betta', baseline: 1, fishFlavor: 'aw, i was hoping for an alpha...', fishColor: hType.pink},
	{fishName: 'Blue Whale', baseline: 4200000, fishFlavor: 'i wonder what makes them so sad?', fishColor: hType.blue},
	{fishName: 'Bluegill', baseline: 16, fishFlavor: "not sure who gill is, but i'm jealous...", fishColor: hType.blue},
	{fishName: 'Carp', baseline: 400, fishFlavor: 'i think i stepped in dog carp...', fishColor: hType.brown},
	{fishName: 'Catfish', baseline: 50, fishFlavor: 'meowzers, thats a weird looking fish...', fishColor: hType.navy},
	{fishName: 'Clownfish', baseline: 3 , fishFlavor:  'reminds me of you, for some reason...', fishColor: hType.orange},
	{fishName: 'Cod', baseline: 350, fishFlavor: "are you there, cod? it's me, margret.", fishColor: hType.navy},
	{fishName: 'Electric Eel', baseline: 704, fishFlavor: 'i said OOH GIRL... shock me like an electric eel!', fishColor: hType.yellow},
	{fishName: 'Flounder', baseline: 10, fishFlavor: "hopefully ariel doesn't mind...", fishColor: hType.yellow},
	{fishName: 'Flying Fish', baseline: 12, fishFlavor: 'this one happened to be swimming, though...', fishColor: hType.navy},
	{fishName: 'Goldfish', baseline: 15, fishFlavor: '24 carrots!', fishColor: hType.orange},
	{fishName: 'Great White', baseline: 25000, fishFlavor: "you're gonna need a bigger boat...", fishColor: hType.white},
	{fishName: 'Guppy', baseline: 0.1, fishFlavor: 'guppy? yuppy!         ...tough crowd...', fishColor: hType.navy},
	{fishName: 'Halibut', baseline: 950, fishFlavor: "i ain't no halibut girl!", fishColor: hType.navy},
	{fishName: 'Hammerhead', baseline: 8100, fishFlavor: 'for some reason, everything looks like a nail now...', fishColor: hType.gray},
	{fishName: 'Herring (Red)', baseline: 37, fishFlavor: "can't help but feel like i'm missing something...", fishColor: hType.red},
	{fishName: 'Jellyfish', baseline: 8, fishFlavor: 'perfect with peanutbutter and bread!', fishColor: hType.normal},
	{fishName: 'Koi', baseline: 175, fishFlavor: "now that's what i call a coy fish!", fishColor: hType.orange},
	{fishName: 'Kraken', baseline: 5000000, fishFlavor: 'wait, what? how?', fishColor: hType.gold},
	{fishName: 'Largemouth Bass', baseline: 45, fishFlavor: 'reminds me of you, for some reason...', fishColor: hType.navy},
	{fishName: 'Lionfish', baseline: 40, fishFlavor: "mane dish at tonight's dinner...", fishColor: hType.orange},
	{fishName: 'Mackerel', baseline: 35, fishFlavor: 'holy mackerel!', fishColor: hType.navy},
	{fishName: 'Mahi-mahi', baseline: 17, fishFlavor: "mahi she's born with it. mahi it's mahilline.", fishColor: hType.green},
	{fishName: 'Sting Ray', baseline: 48000, fishFlavor: "this one's for steve irwin!", fishColor: hType.navy},
	{fishName: 'Marlin', baseline: 16000, fishFlavor: 'famous wizard friend of king arthur.', fishColor: hType.navy},
	{fishName: 'Moray Eel', baseline: 550, fishFlavor: 'i said OOH GIRL... shock me like a moray eel! ...might need work...', fishColor: hType.brown},
	{fishName: 'Oarfish', baseline: 4500, fishFlavor: 'oarfish? morefish, please!', fishColor: hType.silver},
	{fishName: 'Octopus', baseline: 1200, fishFlavor: 'i think the plural is octopussies?', fishColor: hType.red},
	{fishName: 'Perch', baseline: 14, fishFlavor: "get off my perch, youngin'!", fishColor: hType.navy},
	{fishName: 'Pike', baseline: 32, fishFlavor: 'i prefer the halberd, personally.', fishColor: hType.navy},
	{fishName: 'Piranha', baseline: 28, fishFlavor: "my piranha don't want none unless you got buns, hun", fishColor: hType.navy},
	{fishName: 'Pufferfish', baseline: 24, fishFlavor: "pufferfish? i hardley know 'er", fishColor: hType.yellow},
	{fishName: 'Rainbow Trout', baseline: 48, fishFlavor: 'catch the rainbow. taste the rainbow.', fishColor: hType.pink},
	{fishName: 'Red Snapper', baseline: 64, fishFlavor: "at least it's not a herring...", fishColor: hType.red},
	{fishName: 'Sailfish', baseline: 600, fishFlavor: 'sailfish? no, sail boat, EAT fish.', fishColor: hType.navy},
	{fishName: 'Salmon', baseline: 56, fishFlavor: 'more of a blush fushcia, really. or maybe a mauve.', fishColor: hType.red},
	{fishName: 'Sardine', baseline: 5.5, fishFlavor: "i'm starting to feel claustraphobic...", fishColor: hType.navy},
	{fishName: 'Smallmouth Bass', baseline: 39, fishFlavor: "call me benny benassi, because i'm about to DRDRDRDRDRDROP THE BASS!", fishColor: hType.navy},
	{fishName: 'Squid', baseline: 17500, fishFlavor: 'you guys made me ink...', fishColor: hType.orange},
	{fishName: 'Steve', baseline: 4200, fishFlavor: 'cordoz might know more about this one...', fishColor: hType.gold},
	{fishName: 'Sturgeon', baseline: 43, fishFlavor: "i don't care where he got his degree, i'm not letting him operate on me!", fishColor: hType.navy},
	{fishName: 'Sunfish', baseline: 35280, fishFlavor: 'too many fishy one night stands and this is what you get...', fishColor: hType.yellow},
	{fishName: 'Swordfish', baseline: 2400, fishFlavor: 'enguard!', fishColor: hType.navy},
	{fishName: 'Tetra', baseline: 0.05, fishFlavor: 'where are the other three...?', fishColor: hType.green},
	{fishName: 'Tuna', baseline: 8000, fishFlavor: 'favorite of stuffed tigers.', fishColor: hType.navy},
	{fishName: 'Walleye', baseline: 36, fishFlavor: 'big brother is watching...', fishColor: hType.navy},
	{fishName: 'Yellowtail', baseline: 250, fishFlavor: "it's a lot like yellow snow, i don't think you should eat it...", fishColor: hType.yellow},
];
