import type { FishCatalogEntry } from '../../defs/def-record';

export const defaultFishCatalog: FishCatalogEntry[] = [
	{fishName: 'Anchovy', baseline: 2.5, fishFlavor: 'i like them on pizza!'},
	{fishName: 'Angelfish', baseline: 6, fishFlavor: 'i bet it tastes heavenly!'},
	{fishName: 'Barracuda', baseline: 200, fishFlavor: 'how much barra cuda barracuda barra if a barracuda cuda barra?'},
	{fishName: 'Betta', baseline: 1, fishFlavor: 'aw, i was hoping for an alpha...'},
	{fishName: 'Blue Whale', baseline: 4200000, fishFlavor: 'i wonder what makes them so sad?'},
	{fishName: 'Bluegill', baseline: 16, fishFlavor: "not sure who gill is, but i'm jealous..."},
	{fishName: 'Carp', baseline: 400, fishFlavor: 'i think i stepped in dog carp...'},
	{fishName: 'Catfish', baseline: 50, fishFlavor: 'meowzers, thats a weird looking fish...'},
	{fishName: 'Clownfish', baseline: 3 , fishFlavor:  'reminds me of you, for some reason...'},
	{fishName: 'Cod', baseline: 350, fishFlavor: "are you there, cod? it's me, margret."},
	{fishName: 'Electric Eel', baseline: 704, fishFlavor: 'i said OOH GIRL... shock me like an electric eel!'},
	{fishName: 'Flounder', baseline: 10, fishFlavor: "hopefully ariel doesn't mind..."},
	{fishName: 'Flying Fish', baseline: 12, fishFlavor: 'this one happened to be swimming, though...'},
	{fishName: 'Goldfish', baseline: 15, fishFlavor: '24 carrots!'},
	{fishName: 'Great White', baseline: 25000, fishFlavor: "you're gonna need a bigger boat..."},
	{fishName: 'Guppy', baseline: 0.1, fishFlavor: 'guppy? yuppy!         ...tough crowd...'},
	{fishName: 'Halibut', baseline: 950, fishFlavor: "i ain't no halibut girl!"},
	{fishName: 'Hammerhead', baseline: 8100, fishFlavor: 'for some reason, everything looks like a nail now...'},
	{fishName: 'Herring (Red)', baseline: 37, fishFlavor: "can't help but feel like i'm missing something..."},
	{fishName: 'Jellyfish', baseline: 8, fishFlavor: 'perfect with peanutbutter and bread!'},
	{fishName: 'Koi', baseline: 175, fishFlavor: "now that's what i call a coy fish!"},
	{fishName: 'Kraken', baseline: 5000000, fishFlavor: 'wait, what? how?'},
	{fishName: 'Largemouth Bass', baseline: 45, fishFlavor: 'reminds me of you, for some reason...'},
	{fishName: 'Lionfish', baseline: 40, fishFlavor: "mane dish at tonight's dinner..."},
	{fishName: 'Mackerel', baseline: 35, fishFlavor: 'holy mackerel!'},
	{fishName: 'Mahi-mahi', baseline: 17, fishFlavor: "mahi she's born with it. mahi it's mahilline."},
	{fishName: 'Sting Ray', baseline: 48000, fishFlavor: "this one's for steve irwin!"},
	{fishName: 'Marlin', baseline: 16000, fishFlavor: 'famous wizard friend of king arthur.'},
	{fishName: 'Moray Eel', baseline: 550, fishFlavor: 'i said OOH GIRL... shock me like a moray eel! ...might need work...'},
	{fishName: 'Oarfish', baseline: 4500, fishFlavor: 'oarfish? morefish, please!'},
	{fishName: 'Octopus', baseline: 1200, fishFlavor: 'i think the plural is octopussies?'},
	{fishName: 'Perch', baseline: 14, fishFlavor: "get off my perch, youngin'!"},
	{fishName: 'Pike', baseline: 32, fishFlavor: 'i prefer the halberd, personally.'},
	{fishName: 'Piranha', baseline: 28, fishFlavor: "my piranha don't want none unless you got buns, hun"},
	{fishName: 'Pufferfish', baseline: 24, fishFlavor: "pufferfish? i hardley know 'er"},
	{fishName: 'Rainbow Trout', baseline: 48, fishFlavor: 'catch the rainbow. taste the rainbow.'},
	{fishName: 'Red Snapper', baseline: 64, fishFlavor: "at least it's not a herring..."},
	{fishName: 'Sailfish', baseline: 600, fishFlavor: 'sailfish? no, sail boat, EAT fish.'},
	{fishName: 'Salmon', baseline: 56, fishFlavor: 'more of a blush fushcia, really. or maybe a mauve.'},
	{fishName: 'Sardine', baseline: 5.5, fishFlavor: "i'm starting to feel claustraphobic..."},
	{fishName: 'Smallmouth Bass', baseline: 39, fishFlavor: "call me benny benassi, because i'm about to DRDRDRDRDRDROP THE BASS!"},
	{fishName: 'Squid', baseline: 17500, fishFlavor: 'you guys made me ink...'},
	{fishName: 'Steve', baseline: 4200, fishFlavor: 'cordoz might know more about this one...'},
	{fishName: 'Sturgeon', baseline: 43, fishFlavor: "i don't care where he got his degree, i'm not letting him operate on me!"},
	{fishName: 'Sunfish', baseline: 35280, fishFlavor: 'too many fishy one night stands and this is what you get...'},
	{fishName: 'Swordfish', baseline: 2400, fishFlavor: 'enguard!'},
	{fishName: 'Tetra', baseline: 0.05, fishFlavor: 'where are the other three...?'},
	{fishName: 'Tuna', baseline: 8000, fishFlavor: 'favorite of stuffed tigers.'},
	{fishName: 'Walleye', baseline: 36, fishFlavor: 'big brother is watching...'},
	{fishName: 'Yellowtail', baseline: 250, fishFlavor: "it's a lot like yellow snow, i don't think you should eat it..."},
];
